# Generated by Django 2.2.3 on 2019-07-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Deployment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deployment_created", models.DateTimeField(editable=False)),
                ("deployment_time", models.DateTimeField(blank=True, null=True)),
                ("deployment_created_by", models.TextField(blank=True, default="")),
            ],
        )
    ]
